name: Build Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    # - name: Show Tool Versions
    #   run: |
    #     ldd --version
    #     strings /lib/x86_64-linux-gnu/libc.so.6 | grep "GLIBC"
    #     rustc --version
    #     cargo --version

    - name: Run Tests
      run: cargo test -- --nocapture

    - name: Build Library
      run: bash ./buildso.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: yengine
        path: target/release/libyengine.so
